# NOTE: update this with your service name
service: movie-reviews-be

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get